# Generated by Django 4.0.4 on 2022-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('status', models.CharField(default='', max_length=30)),
                ('menuitems', models.ManyToManyField(blank=True, to='menu.menuitem')),
            ],
        ),
    ]
