# Generated by Django 4.0.4 on 2022-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'placed'), ('preparing', 'preparing'), ('ready', 'ready')], max_length=10, null=True),
        ),
    ]
